name = "test-123456"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test-123456_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test-123456.wasm"
command = "npm run build:release"
